version: '3.8'

services:

  db:
    image: postgres:9.4
    volumes:
      - pssql-data:/var/lib/postgresql/data
    networks:
      - backend
    deploy:
      replicas: 1
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_HOST_AUTH_METHOD: trust

  redis:
    image: redis:3.2
    deploy:
      replicas: 1
    networks:
      - frontend
    depends_on:
      - db

  vote:
    image: hiep4hiep/votingapp_vote
    deploy:
      replicas: 3
    ports:
      - "8080:80"
    networks:
      - frontend
    depends_on:
      - db
      - redis

  worker:
    image: hiep4hiep/votingapp_worker
    deploy:
      replicas: 1
    networks:
      - frontend
      - backend
    depends_on:
      - db
      - redis

  result:
    image: hiep4hiep/votingapp_result
    deploy:
      replicas: 1
    ports:
      - 5001:80
    networks:
      - backend
    depends_on:
      - db
      - redis

volumes:
  pssql-data:


networks:
  frontend:
  backend:
